# -*- coding: utf-8 -*-
{
    'name': 'Open HRMS Update Core',
    'version': '13.0.1.2.1',
    'summary': """Open HRMS Update Suit: It brings all Open HRMS Update modules""",
    'description': """It brings all Open HRMS Update modules""",
    'category': 'Generic Modules/Human Resources',
    'author': 'Qzhub',
    'company': 'Qzhub',
    'website': "https://www.qzhub.com",
    'depends': ['hr',
                'attendance_regularization_update',
                'oh_employee_documents_expiry_update',
                'hr_employee_updation_update',
                'hr_custody_update',
                'hr_disciplinary_tracking_update',
                'hr_employee_transfer_update',
                'hr_payroll_community_update',
                'hr_resignation_update',
                'hr_reward_warning_update',
                'hrms_dashboard_update',
                'insurance_management_cybro_update',
                'medical_lab_management_update',
                'oh_appraisal_update',
                'qzhub_spider_widget',
                'website_slides_update',
                ],

    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
